# Generated by Django 6.0.3 on 2026-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
